# Generated by Django 5.2.1 on 2025-06-06 22:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidaciones', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='liquidacion',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='liquidacion',
            constraint=models.UniqueConstraint(fields=('tecnico', 'mes', 'año'), name='unique_liquidacion_por_tecnico_mes_anio', violation_error_message='Ya existe una liquidación para este técnico en ese mes y año.'),
        ),
    ]
